Make the SMTP Server follow the spec
creelonestudios/mailverse pull request #6
Opened 2023-04-26 14:31 UTC by cfpwastaken

Currently, some things in the SMTP Server do not exactly match the spec.

2023-04-26 18:12 UTC, j0code reviewed
yeah, I'm doing something better atm, so close ig

Edit: don't close, changes requested below

2023-04-26 18:12 UTC, cfpwastaken commented
what do you mean

2023-04-26 19:50 UTC, j0code requested changes
everything I did not comment looks good and will be approved

2023-04-26 19:50 UTC, j0code commented on src/smtp/SMTPServer.ts
> +	]);
remove

2023-04-26 19:50 UTC, j0code commented on src/smtp/SMTPServer.ts
> +					sock.write(`250 ${this.messages.get(250)}\r\n`)
undo

2023-04-26 19:50 UTC, j0code commented on src/smtp/SMTPServer.ts
> +				sock.write(`250 ${this.messages.get(250)}\r\n`)
undo

2023-04-26 19:50 UTC, j0code commented on src/smtp/SMTPServer.ts
> +				sock.write(`250 ${this.messages.get(250)}\r\n`)
undo

2023-04-26 19:50 UTC, j0code commented on src/smtp/SMTPServer.ts
> +					sock.write(`503 ${this.messages.get(503)}\r\n`)
undo

2023-04-26 19:50 UTC, j0code commented on src/smtp/SMTPServer.ts
> +					sock.write(`550 ${this.messages.get(550)}\r\n`)
undo

2023-04-26 19:50 UTC, j0code commented on src/smtp/SMTPServer.ts
> +					sock.write(`550 ${this.messages.get(550)}\r\n`)
undo

2023-04-26 19:50 UTC, j0code commented on src/smtp/SMTPServer.ts
> +					sock.write(`554 ${this.messages.get(554)}\r\n`)
undo

2023-04-26 19:50 UTC, j0code commented on src/smtp/SMTPServer.ts
> +				sock.write(`354 ${this.messages.get(354)}\r\n`)
undo

2023-04-26 19:50 UTC, j0code commented on src/smtp/SMTPServer.ts
> +				sock.write(`221 ${this.messages.get(221)}\r\n`)
undo

2023-04-26 19:50 UTC, j0code commented on src/smtp/SMTPServer.ts
> +				sock.write(`502 ${this.messages.get(502)}\r\n`)
```suggestion
				sock.write("502 Command not implemented\r\n")
```

2023-04-26 19:50 UTC, j0code commented on src/smtp/SMTPServer.ts
> +				sock.write(`502 ${this.messages.get(502)}\r\n`)
```suggestion
				sock.write("502 Command not implemented\r\n")
```

2023-04-26 19:50 UTC, j0code commented on src/smtp/SMTPServer.ts
> +				sock.write(`500 ${this.messages.get(500)}\r\n`)
undo

2023-04-28 10:06 UTC, j0code approved these changes
approved, potential conflicts are your responsibility to resolve

2023-04-28 10:07 UTC, cfpwastaken commented
will do, i will merge changes into your branch.

2023-04-28 10:07 UTC, merged