status() for SMTPServer
creelonestudios/mailverse pull request #8
Opened 2023-04-26 19:17 UTC by j0code

2023-04-27 16:48 UTC, cfpwastaken requested changes

2023-04-27 16:48 UTC, cfpwastaken commented on src/main.ts
> +// 	name: "Certified Milkshake",
```suggestion
// 	name: "Cfp",
```

2023-04-27 16:48 UTC, cfpwastaken commented on src/smtp/status.ts
> +	"451 4.4.1":  { code: 451, ok: false, message: "IMAP server unavailable",                  class: 4, subject: 4, detail: 1 },
We dont have IMAP yet??

2023-04-27 16:52 UTC, j0code commented on src/main.ts
> +const pop3server = new POP3Server(getConfig("pop3_port")) // Port 110 for regular POP3, 995 for POP3S
for testing duh
we can put default port tho
```suggestion
export const smtpserver = new SMTPServer(getConfig("smtp_port"), 25) // Port 25 for regular SMTP, 465 for SMTPS
const pop3server = new POP3Server(getConfig("pop3_port"), 110) // Port 110 for regular POP3, 995 for POP3S
```

2023-04-27 16:52 UTC, j0code commented on src/smtp/status.ts
> +	"451 4.4.1":  { code: 451, ok: false, message: "IMAP server unavailable",                  class: 4, subject: 4, detail: 1 },
I added all the common ones.

2023-04-27 16:52 UTC, cfpwastaken commented on src/main.ts
> +const pop3server = new POP3Server(getConfig("pop3_port")) // Port 110 for regular POP3, 995 for POP3S
Sure.

2023-04-27 16:53 UTC, cfpwastaken approved these changes
Approved.

2023-04-27 16:54 UTC, cfpwastaken commented
Github doesnt seem to like the fact that I made that commit. You gotta make a review too.

2023-04-28 10:08 UTC, cfpwastaken commented
I will merge main into this branch now. Do not touch.

2023-04-28 10:34 UTC, cfpwastaken requested changes
rest looks good

2023-04-28 10:34 UTC, cfpwastaken commented on src/smtp/SMTPServer.ts
> +					console.log("[SMTP] No longer receiving data -----------------------------------")
```suggestion
					logger.log("[SMTP] No longer receiving data -----------------------------------")
```

2023-04-28 10:37 UTC, cfpwastaken approved these changes

2023-04-28 10:46 UTC, merged