✨ SMTP Authentication
creelonestudios/mailverse pull request #80
Opened 2024-03-23 17:21 UTC by cfpwastaken

Authentication for outgoing SMTP mail (MAIL FROM our host) as described in [RFC 4954](https://datatracker.ietf.org/doc/html/rfc4954) and PLAIN authentication as described in [RFC 4616](https://datatracker.ietf.org/doc/html/rfc4616).

2024-03-23 17:21 UTC, cfpwastaken commented on src/smtp/SMTPServer.ts
> +			const [_, username, password] = Buffer.from(msg, "base64").toString().split("\0")
Don't think this is getting fixed anytime soon

2024-03-24 11:54 UTC, j0code requested changes
one small tweak
will approve after

2024-03-24 11:54 UTC, j0code commented on src/smtp/SMTPServer.ts
> +import sendStatus, { StatusOptions } from "./status.js"
```suggestion
import sendStatus, { type StatusOptions } from "./status.js"
```

2024-03-24 13:40 UTC, j0code requested changes
minor changes

2024-03-24 13:40 UTC, j0code commented on src/smtp/SMTPServer.ts
> +			state: 0,
can you make this an Enum or at least a Union type, e.g. `"off" | "waiting" | "authenticated"`

2024-03-24 13:40 UTC, j0code commented on src/smtp/SMTPServer.ts
>  				const email = msg.split(":")[1].split(">")[0].replace("<", "")
```suggestion
				const email = msg.substring(msg.indexOf("<") + 1, msg.lastIndexOf(">"))
```
should work
test first though

2024-03-24 14:53 UTC, j0code approved these changes

2024-03-24 14:53 UTC, merged